env:
  BUILDKITE_DOCKER: true
  BUILDKITE_DOCKER_FILE: Dockerfile.ci

steps:
  - command: make ci
    label: :cogops: Testing :elixir: Using :docker: on :buildkite:!!! :joy:
    agents:
      - docker=1.12.1
